server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 

#路由网关：主启动类@EnableZuulProxy
zuul: 
  routes:
    #启用路由通过http://myzuul.com:9527/microservicecloud-dept/dept/get/2访问
    #不启用路由通过http://localhost:8001/dept/get/2访问
    mydept.serviceId: microservicecloud-dept
    #代理名为mydept,访问地址http://myzuul.com:9527/mydept/dept/get/1
    mydept.path: /mydept/** 
  #设置这项，单个设置原名：ignored-services:microservicecloud-dept,多个设置ignored-services:"*"，
  #所有其它原服务名不能访问，不设置则原服务名和代理名称都能访问到
  ignored-services: "*"
  #设置访问前缀，http://myzuul.com:9527/wzw/mydept/dept/get/1  
  prefix: /wzw
 
info:
  app.name: wzw-microcloud
  company.name: www.wzw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
